name: reconnect
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  smooth_star_rating: ^1.1.1
  shared_preferences: ^2.0.15
  google_sign_in: ^5.4.1
  font_awesome_flutter: ^10.1.0  
  fluttertoast: ^8.0.9
  animated_splash_screen:
  dialog_flowtter:
  url_launcher:
  charts_flutter: ^0.12.0
  pie_chart: ^5.3.2
  firebase_storage: ^10.3.7
  file_picker: ^5.0.1
  provider: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.10.0
  flutter_app_name: ^0.1.1
  cloud_firestore: 
  firebase_core: ^1.20.1 
  firebase_auth: ^3.6.3

flutter_icons:
  image_path: "assets/reconnect.jpg"
  android: true
  ios: true

flutter_app_name:
  name: "Reconnect"
  android: true
  ios: true

flutter_lints: ^2.0.0

flutter:

  assets:
    - assets/Reconnect.jpg
    - assets/dialog_flow_auth.json

  uses-material-design: true